
[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
# args = ["--login", "-c", "zellij -l welcome"]

[window]
padding.x = 10
padding.y = 10
option_as_alt = "OnlyLeft"
decorations = "Full"
# decorations = "Buttonless"
startup_mode = "Windowed"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[font]
normal.family = "Cascadia Mono NF"
bold.family = "Cascadia Mono NF"
italic.family = "Cascadia Mono NF"
bold_italic.family = "Cascadia Mono NF"

size = 14.0

[general]
import = ["~/.config/alacritty/themes/nightfox.toml"]

[terminal]
